# Import Library
import requests
import re

# Setting variables needed
username = 'natas27'
password = '55TBjpPZUUJgVP5b3BnbG6ON9uDPVzCJ'

url=f'http://{username}.natas.labs.overthewire.org/'
pw = []

# Connect to natas
session = requests.session()
response = session.get(url, auth=(username,password))

#The Cookie of 'drawing' is generated by the file 'natas26_tool.php'
response = session.request('POST', url, auth=(username,password))

print(response.text)
